// Admin/src/app/pages/khanyi/estate-form/estate-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { EstateService } from 'src/app/core/services/estate.service';
import { Estate, EstateCreateRequest, EstateUpdateRequest, EstateType } from 'src/app/core/models/estate.interface';

@Component({
  selector: 'app-estate-form',
  templateUrl: './estate-form.component.html',
  styleUrls: ['./estate-form.component.scss']
})
export class EstateFormComponent implements OnInit {
  estateForm: FormGroup;
  isEditMode = false;
  loading = false;
  saving = false;
  error = '';
  estateId: string | null = null;

  estateTypes: EstateType[] = ['Residential', 'Student Housing', 'Mixed Use'];
  availableAmenities = [
    'Swimming Pool', 'Gym', 'Playground', 'Security', 'Garden',
    'Parking', 'Shopping Center', 'Community Hall', 'Sports Court',
    'Laundry', 'Wi-Fi', 'Backup Power', 'Water Tank'
  ];

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private estateService: EstateService
  ) {
    this.estateForm = this.createForm();
  }

  ngOnInit(): void {
    this.estateId = this.route.snapshot.paramMap.get('id');
    this.isEditMode = !!this.estateId;

    if (this.isEditMode && this.estateId) {
      this.loadEstate(this.estateId);
    }
  }

  private createForm(): FormGroup {
    return this.fb.group({
      name: ['', [Validators.required, Validators.maxLength(100)]],
      description: ['', [Validators.maxLength(500)]],
      type: ['Residential', Validators.required],
      address: this.fb.group({
        street: ['', Validators.required],
        suburb: [''],
        city: ['', Validators.required],
        province: ['', Validators.required],
        postalCode: ['', [Validators.required, Validators.pattern(/^\d{4}$/)]],
        country: ['South Africa', Validators.required]
      }),
      coordinates: this.fb.group({
        latitude: [null, [Validators.min(-90), Validators.max(90)]],
        longitude: [null, [Validators.min(-180), Validators.max(180)]]
      }),
      tariff: this.fb.group({
        rate: [0, [Validators.required, Validators.min(0)]],
        currency: ['ZAR', Validators.required],
        unit: ['kWh', Validators.required]
      }),
      amenities: [[]],
      isActive: [true]
    });
  }

  private loadEstate(id: string): void {
    this.loading = true;
    this.error = '';

    this.estateService.getEstateById(id).subscribe({
      next: (estate) => {
        this.populateForm(estate);
        this.loading = false;
      },
      error: (error) => {
        this.error = 'Failed to load estate details. Please try again.';
        this.loading = false;
        console.error('Error loading estate:', error);
      }
    });
  }

  private populateForm(estate: Estate): void {
    this.estateForm.patchValue({
      name: estate.name,
      description: estate.description || '',
      type: estate.type,
      address: {
        street: estate.address.street,
        suburb: estate.address.suburb || '',
        city: estate.address.city,
        province: estate.address.province,
        postalCode: estate.address.postalCode,
        country: estate.address.country
      },
      coordinates: {
        latitude: estate.coordinates?.latitude || null,
        longitude: estate.coordinates?.longitude || null
      },
      tariff: {
        rate: estate.tariff.rate,
        currency: estate.tariff.currency,
        unit: estate.tariff.unit
      },
      amenities: estate.amenities || [],
      isActive: estate.isActive
    });
  }

  onAmenityToggle(amenity: string): void {
    const amenities = this.estateForm.get('amenities')?.value || [];
    const index = amenities.indexOf(amenity);

    if (index > -1) {
      amenities.splice(index, 1);
    } else {
      amenities.push(amenity);
    }

    this.estateForm.patchValue({ amenities });
  }

  isAmenitySelected(amenity: string): boolean {
    const amenities = this.estateForm.get('amenities')?.value || [];
    return amenities.includes(amenity);
  }

  onSubmit(): void {
    if (this.estateForm.invalid) {
      this.markFormGroupTouched();
      return;
    }

    this.saving = true;
    this.error = '';

    const formValue = this.estateForm.value;

    if (this.isEditMode && this.estateId) {
      this.updateEstate(this.estateId, formValue);
    } else {
      this.createEstate(formValue);
    }
  }

  private createEstate(formValue: any): void {
    // Clean up optional fields to avoid sending empty strings
    const cleanAddress = {
      street: formValue.address.street,
      city: formValue.address.city,
      province: formValue.address.province,
      postalCode: formValue.address.postalCode,
      country: formValue.address.country,
      ...(formValue.address.suburb && formValue.address.suburb.trim() && {
        suburb: formValue.address.suburb.trim()
      })
    };

    const createRequest: EstateCreateRequest = {
      name: formValue.name,
      type: formValue.type,
      address: cleanAddress,
      coordinates: formValue.coordinates.latitude && formValue.coordinates.longitude
        ? formValue.coordinates
        : undefined,
      tariff: formValue.tariff,
      amenities: formValue.amenities
    };

    // Only include description if it's not empty
    if (formValue.description && formValue.description.trim()) {
      createRequest.description = formValue.description.trim();
    }

    this.estateService.createEstate(createRequest).subscribe({
      next: (estate) => {
        console.log('Estate created successfully:', estate);
        this.router.navigate(['/khanyi/estates']);
      },
      error: (error) => {
        this.error = 'Failed to create estate. Please try again.';
        this.saving = false;
        console.error('Error creating estate:', error);
      }
    });
  }

  private updateEstate(id: string, formValue: any): void {
    // Clean up optional fields to avoid sending empty strings
    const cleanAddress = {
      street: formValue.address.street,
      city: formValue.address.city,
      province: formValue.address.province,
      postalCode: formValue.address.postalCode,
      country: formValue.address.country,
      ...(formValue.address.suburb && formValue.address.suburb.trim() && {
        suburb: formValue.address.suburb.trim()
      })
    };

    const updateRequest: EstateUpdateRequest = {
      name: formValue.name,
      type: formValue.type,
      address: cleanAddress,
      coordinates: formValue.coordinates.latitude && formValue.coordinates.longitude
        ? formValue.coordinates
        : undefined,
      tariff: formValue.tariff,
      amenities: formValue.amenities,
      isActive: formValue.isActive
    };

    // Only include description if it's not empty
    if (formValue.description && formValue.description.trim()) {
      updateRequest.description = formValue.description.trim();
    }

    this.estateService.updateEstate(id, updateRequest).subscribe({
      next: (estate) => {
        console.log('Estate updated successfully:', estate);
        this.router.navigate(['/khanyi/estates']);
      },
      error: (error) => {
        this.error = 'Failed to update estate. Please try again.';
        this.saving = false;
        console.error('Error updating estate:', error);
      }
    });
  }

  private markFormGroupTouched(): void {
    Object.keys(this.estateForm.controls).forEach(key => {
      const control = this.estateForm.get(key);
      control?.markAsTouched();

      if (control?.hasError && typeof control.hasError === 'function') {
        // Handle nested form groups
        if (key === 'address' || key === 'coordinates' || key === 'tariff') {
          Object.keys((control as FormGroup).controls).forEach(nestedKey => {
            (control as FormGroup).get(nestedKey)?.markAsTouched();
          });
        }
      }
    });
  }

  onCancel(): void {
    this.router.navigate(['/khanyi/estates']);
  }

  getFieldError(fieldName: string): string {
    const field = this.estateForm.get(fieldName);
    if (field?.errors && field.touched) {
      if (field.errors['required']) return `${fieldName} is required`;
      if (field.errors['minlength']) return `${fieldName} must be at least ${field.errors['minlength'].requiredLength} characters`;
      if (field.errors['maxlength']) return `${fieldName} must be no more than ${field.errors['maxlength'].requiredLength} characters`;
      if (field.errors['min']) return `${fieldName} must be greater than ${field.errors['min'].min}`;
      if (field.errors['max']) return `${fieldName} must be less than ${field.errors['max'].max}`;
      if (field.errors['pattern']) return `${fieldName} format is invalid`;
    }
    return '';
  }

  getNestedFieldError(groupName: string, fieldName: string): string {
    const field = this.estateForm.get(`${groupName}.${fieldName}`);
    if (field?.errors && field.touched) {
      if (field.errors['required']) return `${fieldName} is required`;
      if (field.errors['min']) return `${fieldName} must be greater than ${field.errors['min'].min}`;
      if (field.errors['max']) return `${fieldName} must be less than ${field.errors['max'].max}`;
      if (field.errors['pattern']) {
        if (fieldName === 'postalCode') return 'Postal code must be exactly 4 digits';
        return `${fieldName} format is invalid`;
      }
    }
    return '';
  }
}

<div class="container-fluid p-4">
  <div class="row">
    <div class="col-12">
      <!-- Page Header -->
      <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
          <h4 class="text-dark mb-1">
            <i class="mdi mdi-home-city text-success me-2"></i>
            {{ isEditMode ? 'Edit Estate' : 'Add New Estate' }}
          </h4>
          <p class="text-muted mb-0">
            {{ isEditMode ? 'Update estate information and settings' : 'Create a new estate for electricity distribution' }}
          </p>
        </div>
        <button type="button" class="btn btn-outline-secondary" (click)="onCancel()">
          <i class="mdi mdi-arrow-left me-1"></i>
          Back to Estates
        </button>
      </div>

      <!-- Loading State -->
      <div *ngIf="loading" class="text-center py-5">
        <div class="spinner-border text-success" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        <p class="mt-3 text-muted">Loading estate details...</p>
      </div>

      <!-- Error Alert -->
      <div *ngIf="error" class="alert alert-danger" role="alert">
        <i class="mdi mdi-alert-circle me-2"></i>
        {{ error }}
      </div>

      <!-- Estate Form -->
      <div class="card border-0 shadow-sm" *ngIf="!loading">
        <div class="card-body p-4">
          <form [formGroup]="estateForm" (ngSubmit)="onSubmit()">

            <!-- Basic Information -->
            <div class="row mb-4">
              <div class="col-12">
                <h5 class="text-dark mb-3">
                  <i class="mdi mdi-information-outline text-primary me-2"></i>
                  Basic Information
                </h5>
              </div>

              <div class="col-md-6 mb-3">
                <label class="form-label fw-semibold">Estate Name *</label>
                <input
                  type="text"
                  class="form-control"
                  formControlName="name"
                  placeholder="Enter estate name"
                  maxlength="100"
                  [class.is-invalid]="getFieldError('name')"
                >
                <div class="invalid-feedback">{{ getFieldError('name') }}</div>
                <small class="form-text text-muted">Maximum 100 characters</small>
              </div>

              <div class="col-md-6 mb-3">
                <label class="form-label fw-semibold">Estate Type *</label>
                <select class="form-select" formControlName="type">
                  <option *ngFor="let type of estateTypes" [value]="type">{{ type }}</option>
                </select>
              </div>

              <div class="col-12 mb-3">
                <label class="form-label fw-semibold">Description</label>
                <textarea
                  class="form-control"
                  formControlName="description"
                  rows="3"
                  placeholder="Enter estate description"
                  maxlength="500"
                  [class.is-invalid]="getFieldError('description')"
                ></textarea>
                <div class="invalid-feedback">{{ getFieldError('description') }}</div>
                <small class="form-text text-muted">Maximum 500 characters</small>
              </div>
            </div>

            <!-- Address Information -->
            <div class="row mb-4" formGroupName="address">
              <div class="col-12">
                <h5 class="text-dark mb-3">
                  <i class="mdi mdi-map-marker-outline text-info me-2"></i>
                  Address Information
                </h5>
              </div>

              <div class="col-md-6 mb-3">
                <label class="form-label fw-semibold">Street Address *</label>
                <input
                  type="text"
                  class="form-control"
                  formControlName="street"
                  placeholder="Enter street address"
                  [class.is-invalid]="getNestedFieldError('address', 'street')"
                >
                <div class="invalid-feedback">{{ getNestedFieldError('address', 'street') }}</div>
              </div>

              <div class="col-md-6 mb-3">
                <label class="form-label fw-semibold">Suburb</label>
                <input
                  type="text"
                  class="form-control"
                  formControlName="suburb"
                  placeholder="Enter suburb"
                >
              </div>

              <div class="col-md-4 mb-3">
                <label class="form-label fw-semibold">City *</label>
                <input
                  type="text"
                  class="form-control"
                  formControlName="city"
                  placeholder="Enter city"
                  [class.is-invalid]="getNestedFieldError('address', 'city')"
                >
                <div class="invalid-feedback">{{ getNestedFieldError('address', 'city') }}</div>
              </div>

              <div class="col-md-4 mb-3">
                <label class="form-label fw-semibold">Province *</label>
                <select
                  class="form-select"
                  formControlName="province"
                  [class.is-invalid]="getNestedFieldError('address', 'province')"
                >
                  <option value="">Select province</option>
                  <option value="Gauteng">Gauteng</option>
                  <option value="Western Cape">Western Cape</option>
                  <option value="KwaZulu-Natal">KwaZulu-Natal</option>
                  <option value="Eastern Cape">Eastern Cape</option>
                  <option value="Free State">Free State</option>
                  <option value="Limpopo">Limpopo</option>
                  <option value="Mpumalanga">Mpumalanga</option>
                  <option value="North West">North West</option>
                  <option value="Northern Cape">Northern Cape</option>
                </select>
                <div class="invalid-feedback">{{ getNestedFieldError('address', 'province') }}</div>
              </div>

              <div class="col-md-4 mb-3">
                <label class="form-label fw-semibold">Postal Code *</label>
                <input
                  type="text"
                  class="form-control"
                  formControlName="postalCode"
                  placeholder="e.g. 2000"
                  maxlength="4"
                  pattern="[0-9]{4}"
                  title="Please enter exactly 4 digits"
                  [class.is-invalid]="getNestedFieldError('address', 'postalCode')"
                >
                <div class="invalid-feedback">{{ getNestedFieldError('address', 'postalCode') }}</div>
                <small class="form-text text-muted">Enter exactly 4 digits</small>
              </div>
            </div>

            <!-- Coordinates (Optional) -->
            <div class="row mb-4" formGroupName="coordinates">
              <div class="col-12">
                <h5 class="text-dark mb-3">
                  <i class="mdi mdi-crosshairs-gps text-warning me-2"></i>
                  GPS Coordinates (Optional)
                </h5>
              </div>

              <div class="col-md-6 mb-3">
                <label class="form-label fw-semibold">Latitude</label>
                <input
                  type="number"
                  step="any"
                  class="form-control"
                  formControlName="latitude"
                  placeholder="e.g., -26.2041"
                >
              </div>

              <div class="col-md-6 mb-3">
                <label class="form-label fw-semibold">Longitude</label>
                <input
                  type="number"
                  step="any"
                  class="form-control"
                  formControlName="longitude"
                  placeholder="e.g., 28.0473"
                >
              </div>
            </div>

            <!-- Tariff Information -->
            <div class="row mb-4" formGroupName="tariff">
              <div class="col-12">
                <h5 class="text-dark mb-3">
                  <i class="mdi mdi-currency-usd text-success me-2"></i>
                  Electricity Tariff
                </h5>
              </div>

              <div class="col-md-4 mb-3">
                <label class="form-label fw-semibold">Rate *</label>
                <input
                  type="number"
                  step="0.01"
                  min="0"
                  class="form-control"
                  formControlName="rate"
                  placeholder="e.g., 2.50"
                  [class.is-invalid]="getNestedFieldError('tariff', 'rate')"
                >
                <div class="invalid-feedback">{{ getNestedFieldError('tariff', 'rate') }}</div>
              </div>

              <div class="col-md-4 mb-3">
                <label class="form-label fw-semibold">Currency *</label>
                <select class="form-select" formControlName="currency">
                  <option value="ZAR">ZAR (South African Rand)</option>
                  <option value="USD">USD (US Dollar)</option>
                  <option value="EUR">EUR (Euro)</option>
                </select>
              </div>

              <div class="col-md-4 mb-3">
                <label class="form-label fw-semibold">Unit *</label>
                <select class="form-select" formControlName="unit">
                  <option value="kWh">kWh (Kilowatt Hours)</option>
                  <option value="MWh">MWh (Megawatt Hours)</option>
                </select>
              </div>
            </div>

            <!-- Amenities -->
            <div class="row mb-4">
              <div class="col-12">
                <h5 class="text-dark mb-3">
                  <i class="mdi mdi-home-variant-outline text-info me-2"></i>
                  Amenities
                </h5>
                <p class="text-muted mb-3">Select the amenities available at this estate</p>

                <div class="row">
                  <div class="col-md-3 col-sm-6 mb-2" *ngFor="let amenity of availableAmenities">
                    <div class="form-check">
                      <input
                        type="checkbox"
                        class="form-check-input"
                        [id]="'amenity-' + amenity"
                        [checked]="isAmenitySelected(amenity)"
                        (change)="onAmenityToggle(amenity)"
                      >
                      <label class="form-check-label" [for]="'amenity-' + amenity">
                        {{ amenity }}
                      </label>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Status (Edit Mode Only) -->
            <div class="row mb-4" *ngIf="isEditMode">
              <div class="col-12">
                <h5 class="text-dark mb-3">
                  <i class="mdi mdi-toggle-switch-outline text-warning me-2"></i>
                  Status
                </h5>
              </div>

              <div class="col-md-6">
                <div class="form-check form-switch">
                  <input
                    type="checkbox"
                    class="form-check-input"
                    id="isActive"
                    formControlName="isActive"
                  >
                  <label class="form-check-label" for="isActive">
                    Estate is Active
                  </label>
                  <small class="form-text text-muted d-block">
                    Inactive estates will not be available for new tenants
                  </small>
                </div>
              </div>
            </div>

            <!-- Form Actions -->
            <div class="row">
              <div class="col-12">
                <hr class="my-4">
                <div class="d-flex gap-3">
                  <button
                    type="submit"
                    class="btn btn-success px-4"
                    [disabled]="saving || estateForm.invalid"
                  >
                    <span *ngIf="saving" class="spinner-border spinner-border-sm me-2"></span>
                    <i *ngIf="!saving" class="mdi mdi-content-save me-2"></i>
                    {{ saving ? 'Saving...' : (isEditMode ? 'Update Estate' : 'Create Estate') }}
                  </button>

                  <button
                    type="button"
                    class="btn btn-outline-secondary px-4"
                    (click)="onCancel()"
                    [disabled]="saving"
                  >
                    <i class="mdi mdi-close me-2"></i>
                    Cancel
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

// khanyi-admin/src/components/EstateForm.tsx
import React, { useState, useEffect } from 'react';
import { XMarkIcon } from '@heroicons/react/24/outline';
import { estatesAPI } from '../services/api';
import { Estate, CreateEstateForm } from '../types';
import { toast } from 'react-toastify';

interface EstateFormProps {
  isOpen: boolean;
  onClose: () => void;
  estate?: Estate | null;
  onSuccess: () => void;
}

const EstateForm: React.FC<EstateFormProps> = ({ isOpen, onClose, estate, onSuccess }) => {
  const [formData, setFormData] = useState<CreateEstateForm>({
    name: '',
    description: '',
    type: 'Residential',
    address: {
      street: '',
      suburb: '',
      city: '',
      province: 'Gauteng',
      postalCode: ''
    },
    tariff: {
      rate: 0,
      currency: 'ZAR',
      unit: 'kWh'
    },
    management: {
      company: '',
      contactPerson: '',
      phone: '',
      email: ''
    },
    amenities: []
  });

  const [loading, setLoading] = useState(false);
  const [amenityInput, setAmenityInput] = useState('');

  const availableAmenities = [
    'Swimming Pool', 'Gym', 'Security', '24/7 Security', 'Clubhouse', 'Gardens',
    'Parking', 'Covered Parking', 'Playground', 'Tennis Court', 'CCTV',
    'Access Control', 'Elevator', 'Backup Power', 'Fiber Ready', 'Pet Friendly'
  ];

  const provinces = [
    'Gauteng', 'Western Cape', 'KwaZulu-Natal', 'Eastern Cape', 'Free State',
    'Limpopo', 'Mpumalanga', 'North West', 'Northern Cape'
  ];

  const estateTypes = ['Residential', 'Student Housing', 'Mixed Use'];

  // Initialize form data when editing
  useEffect(() => {
    if (estate) {
      setFormData({
        name: estate.name,
        description: estate.description || '',
        type: estate.type,
        address: {
          street: estate.address.street,
          suburb: estate.address.suburb || '',
          city: estate.address.city,
          province: estate.address.province,
          postalCode: estate.address.postalCode || ''
        },
        tariff: {
          rate: estate.tariff.rate,
          currency: estate.tariff.currency,
          unit: estate.tariff.unit
        },
        management: estate.management || {
          company: '',
          contactPerson: '',
          phone: '',
          email: ''
        },
        amenities: estate.amenities || []
      });
    } else {
      // Reset form for new estate
      setFormData({
        name: '',
        description: '',
        type: 'Residential',
        address: {
          street: '',
          suburb: '',
          city: '',
          province: 'Gauteng',
          postalCode: ''
        },
        tariff: {
          rate: 0,
          currency: 'ZAR',
          unit: 'kWh'
        },
        management: {
          company: '',
          contactPerson: '',
          phone: '',
          email: ''
        },
        amenities: []
      });
    }
  }, [estate, isOpen]);

  const handleInputChange = (field: string, value: any) => {
    const keys = field.split('.');
    setFormData(prev => {
      const newData = { ...prev };
      let current: any = newData;

      for (let i = 0; i < keys.length - 1; i++) {
        current = current[keys[i]];
      }

      current[keys[keys.length - 1]] = value;
      return newData;
    });
  };

  const addAmenity = () => {
    if (amenityInput.trim() && !formData.amenities.includes(amenityInput.trim())) {
      setFormData(prev => ({
        ...prev,
        amenities: [...prev.amenities, amenityInput.trim()]
      }));
      setAmenityInput('');
    }
  };

  const removeAmenity = (amenity: string) => {
    setFormData(prev => ({
      ...prev,
      amenities: prev.amenities.filter(a => a !== amenity)
    }));
  };

  const addAvailableAmenity = (amenity: string) => {
    if (!formData.amenities.includes(amenity)) {
      setFormData(prev => ({
        ...prev,
        amenities: [...prev.amenities, amenity]
      }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      let response;
      if (estate) {
        response = await estatesAPI.updateEstate(estate._id, formData);
      } else {
        response = await estatesAPI.createEstate(formData);
      }

      if (response.success) {
        toast.success(estate ? 'Estate updated successfully' : 'Estate created successfully');
        onSuccess();
        onClose();
      } else {
        toast.error('Failed to save estate');
      }
    } catch (error: any) {
      toast.error(error.error || 'Failed to save estate');
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg max-w-4xl w-full max-h-[90vh] overflow-y-auto m-4">
        <div className="flex items-center justify-between p-6 border-b">
          <h3 className="text-lg font-medium text-gray-900">
            {estate ? 'Edit Estate' : 'Create New Estate'}
          </h3>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600"
          >
            <XMarkIcon className="h-6 w-6" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-6">
          {/* Basic Information */}
          <div>
            <h4 className="text-md font-medium text-gray-900 mb-4">Basic Information</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Estate Name *
                </label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => handleInputChange('name', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Estate Type *
                </label>
                <select
                  value={formData.type}
                  onChange={(e) => handleInputChange('type', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                >
                  {estateTypes.map(type => (
                    <option key={type} value={type}>{type}</option>
                  ))}
                </select>
              </div>

              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Description
                </label>
                <textarea
                  value={formData.description}
                  onChange={(e) => handleInputChange('description', e.target.value)}
                  rows={3}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
            </div>
          </div>

          {/* Address Information */}
          <div>
            <h4 className="text-md font-medium text-gray-900 mb-4">Address Information</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Street Address *
                </label>
                <input
                  type="text"
                  value={formData.address.street}
                  onChange={(e) => handleInputChange('address.street', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Suburb
                </label>
                <input
                  type="text"
                  value={formData.address.suburb}
                  onChange={(e) => handleInputChange('address.suburb', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  City *
                </label>
                <input
                  type="text"
                  value={formData.address.city}
                  onChange={(e) => handleInputChange('address.city', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Province *
                </label>
                <select
                  value={formData.address.province}
                  onChange={(e) => handleInputChange('address.province', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                >
                  {provinces.map(province => (
                    <option key={province} value={province}>{province}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Postal Code
                </label>
                <input
                  type="text"
                  value={formData.address.postalCode}
                  onChange={(e) => handleInputChange('address.postalCode', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
            </div>
          </div>

          {/* Tariff Information */}
          <div>
            <h4 className="text-md font-medium text-gray-900 mb-4">Tariff Information</h4>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Rate *
                </label>
                <input
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.tariff.rate}
                  onChange={(e) => handleInputChange('tariff.rate', parseFloat(e.target.value) || 0)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Currency
                </label>
                <select
                  value={formData.tariff.currency}
                  onChange={(e) => handleInputChange('tariff.currency', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="ZAR">ZAR</option>
                  <option value="USD">USD</option>
                  <option value="EUR">EUR</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Unit
                </label>
                <select
                  value={formData.tariff.unit}
                  onChange={(e) => handleInputChange('tariff.unit', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="kWh">kWh</option>
                  <option value="kW">kW</option>
                </select>
              </div>
            </div>
          </div>

          {/* Management Information */}
          <div>
            <h4 className="text-md font-medium text-gray-900 mb-4">Management Information</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Management Company
                </label>
                <input
                  type="text"
                  value={formData.management?.company || ''}
                  onChange={(e) => handleInputChange('management.company', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Contact Person
                </label>
                <input
                  type="text"
                  value={formData.management?.contactPerson || ''}
                  onChange={(e) => handleInputChange('management.contactPerson', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Phone Number
                </label>
                <input
                  type="tel"
                  value={formData.management?.phone || ''}
                  onChange={(e) => handleInputChange('management.phone', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Email Address
                </label>
                <input
                  type="email"
                  value={formData.management?.email || ''}
                  onChange={(e) => handleInputChange('management.email', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
            </div>
          </div>

          {/* Amenities */}
          <div>
            <h4 className="text-md font-medium text-gray-900 mb-4">Amenities</h4>

            {/* Quick Add Buttons */}
            <div className="mb-4">
              <p className="text-sm text-gray-600 mb-2">Quick add:</p>
              <div className="flex flex-wrap gap-2">
                {availableAmenities.map(amenity => (
                  <button
                    key={amenity}
                    type="button"
                    onClick={() => addAvailableAmenity(amenity)}
                    disabled={formData.amenities.includes(amenity)}
                    className={`px-3 py-1 text-xs rounded-full border ${
                      formData.amenities.includes(amenity)
                        ? 'bg-gray-100 text-gray-400 border-gray-200'
                        : 'bg-white text-blue-600 border-blue-200 hover:bg-blue-50'
                    }`}
                  >
                    {amenity}
                  </button>
                ))}
              </div>
            </div>

            {/* Custom Amenity Input */}
            <div className="flex gap-2 mb-4">
              <input
                type="text"
                value={amenityInput}
                onChange={(e) => setAmenityInput(e.target.value)}
                placeholder="Add custom amenity..."
                className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), addAmenity())}
              />
              <button
                type="button"
                onClick={addAmenity}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
              >
                Add
              </button>
            </div>

            {/* Selected Amenities */}
            {formData.amenities.length > 0 && (
              <div>
                <p className="text-sm text-gray-600 mb-2">Selected amenities:</p>
                <div className="flex flex-wrap gap-2">
                  {formData.amenities.map(amenity => (
                    <span
                      key={amenity}
                      className="inline-flex items-center px-3 py-1 text-sm bg-blue-100 text-blue-800 rounded-full"
                    >
                      {amenity}
                      <button
                        type="button"
                        onClick={() => removeAmenity(amenity)}
                        className="ml-2 text-blue-600 hover:text-blue-800"
                      >
                        ×
                      </button>
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Form Actions */}
          <div className="flex justify-end space-x-4 pt-6 border-t">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50"
              disabled={loading}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50"
              disabled={loading}
            >
              {loading ? (
                <div className="flex items-center">
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                  Saving...
                </div>
              ) : (
                estate ? 'Update Estate' : 'Create Estate'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default EstateForm;
